name: "curiejet 3DRP integration"
version: "1.1.26"
slug: "curiejet_integration"
description: "This Home Assistant add-on listens to MQTT messages and dynamically generates 
  MQTT Discovery configurations for CurieJet devices (e.g., 3DRP). 
  It enables seamless integration of sensor and control data from various CurieJet models 
  into your Home Assistant setup."
startup: "services"
boot: "auto"
arch:
  - aarch64
  - amd64
  - armv7
# url: "https://github.com/YJ-spec/3DRP_ADDON"
init: false
ingress: false

# 這行才是關鍵：讓你可以打 http://supervisor/core/api
homeassistant_api: true

# 對外開放 8099
ingress: false
ports:
  "8099/tcp": 8099
ports_description:
  "8099/tcp": "3DRP HTTP API and Status page"

# 在 Add-on 頁面顯示「Open Web UI」按鈕（連到 /status）
webui: "http://[HOST]:[PORT:8099]/status"
panel_icon: "mdi:view-list-outline"

map:
  - share:rw

options:
  mqtt_topics: "+/+/data,+/+/control"
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  # HA_LONG_LIVED_TOKEN: ""

schema:
  mqtt_topics: str
  mqtt_broker: str
  mqtt_port: int
  mqtt_username: str?
  mqtt_password: str?
  # HA_LONG_LIVED_TOKEN: password?
